/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/room.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/room.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Suelo.geometry} material={materials['Material.002']} position={[0, 0.088, 0]} />
      <group position={[0, 3.163, 4.535]}>
        <mesh geometry={nodes.Plane002.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Plane002_1.geometry} material={materials['Material.003']} />
      </group>
      <group position={[-1.855, 0.242, -3.305]}>
        <mesh geometry={nodes.Cube008.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube008_1.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube008_2.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube008_3.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube008_4.geometry} material={materials['Material.008']} />
      </group>
      <group position={[0.325, 1.533, 3.427]}>
        <mesh geometry={nodes.Cube015.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cube015_1.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Cube015_2.geometry} material={materials['Material.010']} />
      </group>
      <group position={[0.328, 1.617, 3.791]}>
        <mesh geometry={nodes.Cube023.geometry} material={materials['Material.014']} />
        <mesh geometry={nodes.Cube023_1.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cube023_2.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cube023_3.geometry} material={materials['Material.014']} />
        <mesh geometry={nodes.Cube023_4.geometry} material={materials.PC_Body} />
        <mesh geometry={nodes.Cube023_5.geometry} material={materials.PC_FrontPanel} />
        <mesh geometry={nodes.Cube023_6.geometry} material={materials.PC_LED_V} />
        <mesh geometry={nodes.Cube023_7.geometry} material={materials.PC_PwrMat} />
        <mesh geometry={nodes.Cube023_8.geometry} material={materials.PC_RstMat} />
        <mesh geometry={nodes.Cube023_9.geometry} material={materials.PC_USB_Mat_0} />
        <mesh geometry={nodes.Cube023_10.geometry} material={materials.PC_USB_Mat_0} />
        <mesh geometry={nodes.Cube023_11.geometry} material={materials.PC_GrillBand} />
        <mesh geometry={nodes.Cube023_12.geometry} material={materials.PC_GrillSlot_0} />
        <mesh geometry={nodes.Cube023_13.geometry} material={materials.PC_GrillSlot_0} />
        <mesh geometry={nodes.Cube023_14.geometry} material={materials.PC_GrillSlot_0} />
        <mesh geometry={nodes.Cube023_15.geometry} material={materials.PC_GrillSlot_0} />
        <mesh geometry={nodes.Cube023_16.geometry} material={materials.PC_Glass_Mat} />
      </group>
      <group position={[0.184, 0.988, 2.465]}>
        <mesh geometry={nodes.Cube006.geometry} material={materials['Material.019']} />
        <mesh geometry={nodes.Cube006_1.geometry} material={nodes.Cube006_1.material} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials['Material.020']} />
      </group>
      <group position={[-3.762, 2.447, 0.834]}>
        <mesh geometry={nodes.Cube018.geometry} material={nodes.Cube018.material} />
        <mesh geometry={nodes.Cube018_1.geometry} material={materials.Material} />
      </group>
      <group position={[0.7, 1.65, 3.55]}>
        <mesh geometry={nodes.Cylinder009.geometry} material={materials.Mat_Taza} />
        <mesh geometry={nodes.Cylinder009_1.geometry} material={materials.Mat_Taza} />
      </group>
      <mesh geometry={nodes.Cafe.geometry} material={materials.Mat_Cafe} position={[0.7, 1.695, 3.55]} />
      <group position={[-0.9, 2.54, 3.8]}>
        <mesh geometry={nodes.Torus.geometry} material={materials.Mat_Gold} />
        <mesh geometry={nodes.Torus_1.geometry} material={materials.Mat_Jarron} />
      </group>
      <group position={[-0.976, 3.07, 3.866]}>
        <mesh geometry={nodes.bsep_Bud_3_0.geometry} material={materials.MSepal} />
        <mesh geometry={nodes.bsep_Bud_3_0_1.geometry} material={materials.Stem} />
        <mesh geometry={nodes.bsep_Bud_3_0_2.geometry} material={materials.Leaf} />
        <mesh geometry={nodes.bsep_Bud_3_0_3.geometry} material={materials.MRed} />
        <mesh geometry={nodes.bsep_Bud_3_0_4.geometry} material={materials.MPink} />
        <mesh geometry={nodes.bsep_Bud_3_0_5.geometry} material={materials.MWhite} />
        <mesh geometry={nodes.bsep_Bud_3_0_6.geometry} material={materials.MBud} />
      </group>
      <mesh geometry={nodes.Raton.geometry} material={materials.Mouse_B} position={[-1.59, -0.01, 0]} />
      <mesh geometry={nodes.Cube032.geometry} material={materials.Mat_Mesita} />
      <mesh geometry={nodes.Cube032_1.geometry} material={materials.Mat_Mesita_Top} />
      <mesh geometry={nodes.Cube032_2.geometry} material={materials.Mat_Tirador} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials.Mat_LampBase} />
      <mesh geometry={nodes.Cylinder_1.geometry} material={materials.Mat_LampBase} />
      <mesh geometry={nodes.Cylinder_2.geometry} material={materials.Mat_Lampara_Shade} />
      <mesh geometry={nodes.Cube131.geometry} material={materials.Mat_Libro_Mid_0_Cover} />
      <mesh geometry={nodes.Cube131_1.geometry} material={materials.Mat_Libro_Top_0_Cover} />
      <mesh geometry={nodes.Cube131_2.geometry} material={materials.Mat_Paginas} />
      <mesh geometry={nodes.Cube131_3.geometry} material={materials.Mat_Libro_Top_0_Banda} />
      <mesh geometry={nodes.Cube131_4.geometry} material={materials.Mat_Libro_Top_0_Banda} />
      <mesh geometry={nodes.Cube131_5.geometry} material={materials.Mat_Libro_Top_1_Cover} />
      <mesh geometry={nodes.Cube131_6.geometry} material={materials.Mat_Paginas} />
      <mesh geometry={nodes.Cube131_7.geometry} material={materials.Mat_Libro_Top_1_Banda} />
      <mesh geometry={nodes.Cube131_8.geometry} material={materials.Mat_Libro_Top_1_Banda} />
      <mesh geometry={nodes.Cube131_9.geometry} material={materials.Mat_Libro_Top_2_Cover} />
      <mesh geometry={nodes.Cube131_10.geometry} material={materials.Mat_Paginas} />
      <mesh geometry={nodes.Cube131_11.geometry} material={materials.Mat_Libro_Top_2_Banda} />
      <mesh geometry={nodes.Cube131_12.geometry} material={materials.Mat_Libro_Top_2_Banda} />
      <mesh geometry={nodes.Cube131_13.geometry} material={materials.Mat_Libro_Top_3_Cover} />
      <mesh geometry={nodes.Cube131_14.geometry} material={materials.Mat_Paginas} />
      <mesh geometry={nodes.Cube131_15.geometry} material={materials.Mat_Libro_Top_3_Banda} />
      <mesh geometry={nodes.Cube131_16.geometry} material={materials.Mat_Libro_Top_3_Banda} />
      <mesh geometry={nodes.Cube131_17.geometry} material={materials.Mat_Libro_Top_4_Cover} />
      <mesh geometry={nodes.Cube131_18.geometry} material={materials.Mat_Paginas} />
      <mesh geometry={nodes.Cube131_19.geometry} material={materials.Mat_Libro_Top_4_Banda} />
      <mesh geometry={nodes.Cube131_20.geometry} material={materials.Mat_Libro_Top_4_Banda} />
      <mesh geometry={nodes.Cube131_21.geometry} material={materials.Mat_Libro_Top_5_Cover} />
      <mesh geometry={nodes.Cube131_22.geometry} material={materials.Mat_Paginas} />
      <mesh geometry={nodes.Cube131_23.geometry} material={materials.Mat_Libro_Top_5_Banda} />
      <mesh geometry={nodes.Cube131_24.geometry} material={materials.Mat_Libro_Top_5_Banda} />
      <mesh geometry={nodes.Cube131_25.geometry} material={materials.Mat_Libro_Top_6_Cover} />
      <mesh geometry={nodes.Cube131_26.geometry} material={materials.Mat_Paginas} />
      <mesh geometry={nodes.Cube131_27.geometry} material={materials.Mat_Libro_Top_6_Banda} />
      <mesh geometry={nodes.Cube131_28.geometry} material={materials.Mat_Libro_Top_6_Banda} />
      <mesh geometry={nodes.Cube131_29.geometry} material={materials.Mat_Libro_Top_7_Cover} />
      <mesh geometry={nodes.Cube131_30.geometry} material={materials.Mat_Paginas} />
      <mesh geometry={nodes.Cube131_31.geometry} material={materials.Mat_Libro_Top_7_Banda} />
      <mesh geometry={nodes.Cube131_32.geometry} material={materials.Mat_Libro_Top_7_Banda} />
      <mesh geometry={nodes.Cube131_33.geometry} material={materials.Mat_Paginas} />
      <mesh geometry={nodes.Cube131_34.geometry} material={materials.Mat_Libro_Mid_0_Banda} />
      <mesh geometry={nodes.Cube131_35.geometry} material={materials.Mat_Libro_Mid_0_Banda} />
      <mesh geometry={nodes.Cube131_36.geometry} material={materials.Mat_Libro_Mid_1_Cover} />
      <mesh geometry={nodes.Cube131_37.geometry} material={materials.Mat_Paginas} />
      <mesh geometry={nodes.Cube131_38.geometry} material={materials.Mat_Libro_Mid_1_Banda} />
      <mesh geometry={nodes.Cube131_39.geometry} material={materials.Mat_Libro_Mid_1_Banda} />
      <mesh geometry={nodes.Cube131_40.geometry} material={materials.Mat_Libro_Mid_2_Cover} />
      <mesh geometry={nodes.Cube131_41.geometry} material={materials.Mat_Paginas} />
      <mesh geometry={nodes.Cube131_42.geometry} material={materials.Mat_Libro_Mid_2_Banda} />
      <mesh geometry={nodes.Cube131_43.geometry} material={materials.Mat_Libro_Mid_2_Banda} />
      <mesh geometry={nodes.Cube131_44.geometry} material={materials.Mat_Libro_Mid_3_Cover} />
      <mesh geometry={nodes.Cube131_45.geometry} material={materials.Mat_Paginas} />
      <mesh geometry={nodes.Cube131_46.geometry} material={materials.Mat_Libro_Mid_3_Banda} />
      <mesh geometry={nodes.Cube131_47.geometry} material={materials.Mat_Libro_Mid_3_Banda} />
      <mesh geometry={nodes.Cube131_48.geometry} material={materials.Mat_Libro_Mid_4_Cover} />
      <mesh geometry={nodes.Cube131_49.geometry} material={materials.Mat_Paginas} />
      <mesh geometry={nodes.Cube131_50.geometry} material={materials.Mat_Libro_Mid_4_Banda} />
      <mesh geometry={nodes.Cube131_51.geometry} material={materials.Mat_Libro_Mid_4_Banda} />
      <mesh geometry={nodes.Cube131_52.geometry} material={materials.Mat_Libro_Mid_5_Cover} />
      <mesh geometry={nodes.Cube131_53.geometry} material={materials.Mat_Paginas} />
      <mesh geometry={nodes.Cube131_54.geometry} material={materials.Mat_Libro_Mid_5_Banda} />
      <mesh geometry={nodes.Cube131_55.geometry} material={materials.Mat_Libro_Mid_5_Banda} />
      <mesh geometry={nodes.Cube131_56.geometry} material={materials.Mat_Libro_Mid_6_Cover} />
      <mesh geometry={nodes.Cube131_57.geometry} material={materials.Mat_Paginas} />
      <mesh geometry={nodes.Cube131_58.geometry} material={materials.Mat_Libro_Mid_6_Banda} />
      <mesh geometry={nodes.Cube131_59.geometry} material={materials.Mat_Libro_Mid_6_Banda} />
      <mesh geometry={nodes.Cube064.geometry} material={materials.KB_Key} />
      <mesh geometry={nodes.Cube064_1.geometry} material={materials.KB_Body} />
      <mesh geometry={nodes.Cube064_2.geometry} material={materials.KB_LED} />
      <mesh geometry={nodes.Cube064_3.geometry} material={materials.KB_Space} />
    </group>
  )
}

useGLTF.preload('/room.glb')
